### ISSUE TITLE
View for mobile devices

### ISSUE THREAD

**Issue by CelynChew** [CelynChew/CITS3403#10]
When the screen gets to a mobile view, the layout of all the pages get very disorganised. 

Probably should add something like `<meta name="viewport" content="width=device-width, initial-scale=1">` to the html templates.

**Comment by Roy-Lam** [comment]
The login and registration page already has `<meta name="viewport" content="width=device-width, initial-scale=1">` while chatroom and tutorial doesn't have it

The first commit added `<meta name="viewport" content="width=device-width, initial-scale=1">` to chatroom while second commit has added it to tutorial page

**Comment by Roy-Lam** [comment]
The navigational bar from bootstrap turns buttons such as logout into dropdown menus (friendly for smaller devices), but buttons on the left side of the chat will still disappear on smaller devices and screens.

**Comment by CelynChew** [comment]
For some of the pages, I created a separate html for mobile view (denoted with `-m`) and created the routes for those. Though might have to look at the security for those routes. Just an issue for the chatroom. It defaults on the desktop view when in mobile size - have to resize it manually by making the webpage smaller. Will continue working on that.

**Comment by bc163836** [comment]
Login Page doesnt return to desktop size when expanded. Need to add a listener that detects when page is resized to return to the desktop login page

**Comment by CelynChew** [comment]
Fixed it by writing separate js codes in the login-register.html and login-m.html
