### ISSUE TITLE
Sending messages

### ISSUE THREAD

**Issue by CelynChew** [CelynChew/CITS3403#11]
The messages are sent when enter key is pressed but it does not send when the send button is clicked on the webpage. Might have to add Event Listeners for 'click' since `sendMessage(chatName)` function requires chat name argument.

**Comment by CelynChew** [comment]
First commit:
-  Fixing it by adding a listener for the `send-button`. 

Second commit:
- Realised that the codes to get chat id and chat name to update the chat display were not needed.

**Comment by Roy-Lam** [comment]
Both ways of sending via pressing enter or clicking the send message button (designed for application such as mobile) is functional. Issue resolved and will be closed.
