### ISSUE TITLE
Can access "login required" routes through URL

### ISSUE THREAD

**Issue by Roy-Lam** [CelynChew/CITS3403#8]
After creating at least 1 user account, user can access chatroom & tutorial through URL eg. (/chatroom, /tutorial). Logging out doesn't stop this issue from happening. The logged in details belongs to the last logged in user.

**Comment by CelynChew** [comment]
Fixed that issue by updating the LoggingOut() in chatroom.js. It's done in the Security Branch. 

Manually tested it and it return a 401 error on the webpage. Do you think if it'd be better if we use alert messages and redirect users to the login page for better user experience?

**Comment by Roy-Lam** [comment]
redirecting user to login page is mandatory while the alert message is optional
