### ISSUE TITLE
Chat display

### ISSUE THREAD

**Issue by CelynChew** [CelynChew/CITS3403#9]
Chat display is buggy when there are 2 or more chats. After sending a message, the chat displayed will automatically show the first chat. Have to manually click onto the chat to see the messages. 

Likely to be an issue with how updateChatDisplay() function in chatroom.js is called.

**Comment by Roy-Lam** [comment]
Issue confirmed, would also suggest greying out send message button and message input bar when no chat is selected.

**Comment by CelynChew** [comment]
Good idea! Will get on that.

**Comment by CelynChew** [comment]
Issue with the the first chat showing is to do with `/get_chat_id` route. The logic always returns chat id 1.
